openapi: 3.1.0
info:
  title: S3 Bucket API's
  description: All API Related to S3.
  version: 3.0
servers:
  - url: http://localhost:8000
    description: Local server   
paths:
  /getobject/objects:
    get:
      summary: Returns a list of Bucket.
      tags:
        - Data
      parameters:
        - in: query
          name: bucketName
          required: true
          schema:
            type: string
            minimum: 1
        - in: query
          name: key
          required: true
          schema:
            type: string
            minimum: 1
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of Bucket
          content:
            application/json:
              schema:
                type: array
                data:
                  type: string
  /deleteobject/objects:
    delete:
      summary: Returns a list of Bucket.
      tags:
        - Data
      parameters:
        - in: query
          name: bucketName
          required: true
          schema:
            type: string
            minimum: 1
        - in: query
          name: key
          required: true
          schema:
            type: string
            minimum: 1
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of Bucket
          content:
            application/json:
              schema:
                type: array
                data:
                  type: string
  /listobject/objects:
    get:
      summary: Returns a list of Bucket.
      tags:
        - Data
      parameters:
        - in: query
          name: bucketName
          required: true
          schema:
            type: string
            minimum: 1
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of Bucket
          content:
            application/json:
              schema:
                type: array
                data:
                  type: string
  /listbuckets:
    get:
      summary: Returns a list of Bucket.
      tags:
        - Data
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of Bucket
          content:
            application/json:
              schema:
                type: array
                data:
                  type: string
  /putobject/objects:
    post:
      summary: Returns a list of Bucket.
      tags:
        - Data
      parameters:
        - in: query
          name: bucketName
          required: true
          schema:
            type: string
            minimum: 1
        - in: query
          name: key
          required: true
          schema:
            type: string
            minimum: 1
        - in: form-data
          name: file
          required: true
          schema:
            type: file
            minimum: 1
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of Bucket
          content:
            application/json:
              schema:
                type: array
                data:
                  type: string

                             
